### ISSUE TITLE
Don't use files in flash

### ISSUE THREAD

**Issue by KOLANICH** [DHM47/Native-Clip-Board#14]
I think that all clipboard must be stored entirely in RAM to reduce flash memory wear.
You can do it with very little effort with help of ```mount -t ramfs -o size=1m ramfs /data/data/com.dhm47.nativeclipboard/files```

**Comment by tgh980122** [comment]
"Mount -t ramfs" will create a ramdisk, but when devices reboot or shutdown,it will lost all things in  it. By the way,not all devices suppose  "mount -t ramdisk.

**Comment by KOLANICH** [comment]
>but when devices reboot or shutdown,it will lost all things in it.
I don't need clipboard persisting reboots. It is not a clipboard.
>By the way,not all devices suppose "mount -t ramdisk.
It is possible to provide this feature only on devices that support.

But a better way is to make a native daemon to store clips in memory, which is not an app, that's why cannot be killed by scheduler.

**Comment by tgh980122** [comment]
Some people may hope that clip data can be stored even devices reboot. And now I must sleep,because I am in the UTC+8 time zone.

--- Tyan Boot 敬上！ ---

--- 原始邮件 ---

发件人： "KOLANICH" <notifications@github.com>
已发： 2015年2月2日 上午1:56
收件人： "DHM47/Native-Clip-Board" <Native-Clip-Board@noreply.github.com>
抄送： "tgh980122" <tyan-boot@outlook.com>
主题： Re: [Native-Clip-Board] Don't use files in flash (#14)

>but when devices reboot or shutdown,it will lost all things in it.
I don't need clipboard persisting reboots. It is not a clipboard.
>By the way,not all devices suppose "mount -t ramdisk.
It is possible to provide this feature only on devices that support.

But a better way is to make a native daemon to store clips in memory, which is not an app, that's why cannot be killed by scheduler.

---

**Comment by DHM47** [comment]
Doesn't the file survive a reboot ?

**Comment by tgh980122** [comment]
Of course.  Ramfs uses RAM to store file,so its file will lost after reboot. It is temporary.

**Comment by KOLANICH** [comment]
BTW: the data in RAM can be alive for some amount of time. The time can be increased using cooling. This can be used for coldboot attack.

**Comment by DHM47** [comment]
Are you still interested in my app ?
The up coming update caches the data in RAM and only writes when needed.

**Comment by KOLANICH** [comment]
Thank you.

**Comment by DHM47** [comment]
I forgot to mention, that's only if you use the app with the Accessibility service. So if you still use it as an xposed module nothing will change. 
So disable the module, and goto the System settings >Accessibility >Native-Clip-Board, and enable it. In addition to not always writing to the storage, see the change log on the Xposed repo

**Comment by DHM47** [comment]
And FYI, (using the accessibility) the app will read the list once at launch, when ever something is copied it's added to the list then written to storage. Or when you change something in the list (pin /unpin, or delete). 
If you don't want it to write to the storage at all (so the list will get cleared after a reboot) use something to disable the "clip monitor service" in my app.

**Comment by KOLANICH** [comment]
1 I prefer to use it through xposed because doubletap trigger causes troubles.
2 How about not writing to flash at all?
3 How about hooking android clipboard to make it not to use flash too?

**Comment by DHM47** [comment]
1-Two additional triggers are in testing (triple tap  and tap+long tap)
2-If you use an app that can disable background services, disable "ClipMonitorService" in my app.
3-I don't think it uses flash

**Comment by KOLANICH** [comment]
1 Ι dislike multiple-tap triggers at all because
A) differrent apps could process them (for example, in web browsers this causes magnification)
B) it is difficult to multiple-tap exactly the same place
A button in clipboard bar (and a fix for firefox too) are better.
2 It'd be better to have a pref in the app than to rely on hacks.
3 Googled a little, recent versions of android really don't use flash to store clipboard.

**Comment by DHM47** [comment]
Can you please send me an email to dhm47.dev@gmail.com

**Comment by KOLANICH** [comment]
>Can you please send me an email to dhm47.dev@gmail.com

I see no reason not to discuss here.

**Comment by DHM47** [comment]
Well I don't check the issue tracker that often so email is just more convenient and faster.
I've asked you this before, can you compile the app yourself ? Do you have Android Studio?  
Because I still don't feel that it would be used my many.

**Comment by KOLANICH** [comment]
>I've asked you this before, can you compile the app yourself ? Do you have Android Studio.
Last time I tried to build an app for android, A.S. had eaten all the free space on the hdd. So, no.

>Well I don't check the issue tracker that often so email is just more convenient and faster.
GH notifies user with email and if you respond it, the comment is added to the issue (the answer by tyan-boot with a letter icon in this issue is the example).

>Because I still don't feel that it would be used my many.
Why do you think so and is it a problem?
