### ISSUE TITLE
Hope limitless history.

### ISSUE THREAD

**Issue by tgh980122** [DHM47/Native-Clip-Board#25]
I think 50 history is too small.So I hope it can be larger even limitless :)

**Comment by DHM47** [comment]
Every One I know thought it was enough, but I can increase it.
How much do you have in mind ? 
I might try to make it like { 1,2,3,4...,49,50,(infinite) } what do you think ?

**Comment by tgh980122** [comment]
It is a good idea

**Comment by DHM47** [comment]
its now (still not released)
1,2,3,...,49,50,75,100,9999
is that good ?

**Comment by tgh980122** [comment]
yes. Today I have thought this,if it becomes infinite,app will use more flash to store data,and some people may be confused why it use so many flash. 
And I think it should show how many items when open a big view.

**Comment by DHM47** [comment]
Space should not be an issue, During testing I filled it with 50,000 clips and it needed just above 1 MB

What do you mean by "And I think it should show how many items when open a big view" ?

**Comment by tgh980122** [comment]
I means that app should show user how many history has been stored in some place,for example top left corner.

**Comment by tgh980122** [comment]
![screenshot_2015-02-03-01-58-00](https://cloud.githubusercontent.com/assets/4982027/6005813/29f8d0c4-ab48-11e4-893a-37120c7b1520.png)
Look this picture.You will understand what i means

**Comment by DHM47** [comment]
I'll think about that, and I am already adding a "+" Button to add clips in the top left corner.
So I'll need to put it in an other place.

**Comment by DHM47** [comment]
Update released in xda thread
