### ISSUE TITLE
Too much height of elements in z axis 

### ISSUE THREAD

**Issue by HankAviator** [DHM47/Native-Clip-Board#31]
Nice try of Material Design! But the elements seem to have been assigned with too much more height in z axis. The shadow is kind of distracting when many items stack together. Maybe 6dp- for ~~*action bar*~~ *App bar* and 2dp- for items is better.

**Comment by tyan-boot** [comment]
Are you Chinese?

**Comment by HankAviator** [comment]
Aye

**Comment by tyan-boot** [comment]
…那你还回复我英文…

**Comment by DHM47** [comment]
What's your device ? (screen size and resolution)
the values looked good on my device.and I didn't find any official recommended values

**Comment by HankAviator** [comment]
![screenshot_2015-03-10-08-14-53](https://cloud.githubusercontent.com/assets/8069557/6569254/bcb050dc-c721-11e4-96d0-4de1ee69077a.png)
![screenshot_2015-03-10-08-15-38](https://cloud.githubusercontent.com/assets/8069557/6569255/bce9842e-c721-11e4-9e17-84a0a49da1b2.png)
In the example of Google Keep, items have 1dp standard thickness and 0dp elevation, therefore only slight border. The card floats only when long tapped, it then has been raised a bit. [Objects in 3D space - Material Design](http://www.google.com/design/spec/what-is-material/objects-in-3d-space.html#objects-in-3d-space-elevation)

![screenshot_2015-03-10-07-57-02](https://cloud.githubusercontent.com/assets/8069557/6569413/b6eeeaca-c724-11e4-8475-cba429b246b9.png)
![screenshot_2015-03-10-08-09-06](https://cloud.githubusercontent.com/assets/8069557/6569414/b71e9f18-c724-11e4-86fb-8339ddba94c7.png)

Google app Now cards also has 2dp elevation, similarly, VK app has 1dp. App bar has an example elevation of 4dp on the page of Material Design. 

My phone: OnePlus One "Bacon", 5.5" @ 1080p. It looks like this on my phone. The shadow of *App bar* (let us call it so) is staggered with the shadows of the first two items' upper edge .

![screenshot_2015-03-10-08-06-11](https://cloud.githubusercontent.com/assets/8069557/6569409/a9b084fe-c724-11e4-872d-6d91a39d8771.png)

**Comment by DHM47** [comment]
Thank you for the link, I changed them accordingly.
After the update is released, if the elevations are good please close the issue.

**Comment by DHM47** [comment]
Update released

**Comment by HankAviator** [comment]
Fabulous!

**Comment by DHM47** [comment]
Yes it's much better, thank you for pointing it out
