### ISSUE TITLE
Across-layer touching

### ISSUE THREAD

**Issue by HankAviator** [DHM47/Native-Clip-Board#33]
![screenshot_2015-03-15-09-37-06](https://cloud.githubusercontent.com/assets/8069557/6656234/94ac515e-cb5d-11e4-9e99-a1059c84db77.png)
Tapped as in the location positioned in the screenshot, the item is pasted into the current textbox. Long tapping will also expand the item.

**Comment by DHM47** [comment]
Which item gets expanded? 
Sorry for the late reply.

**Comment by HankAviator** [comment]
notice the position of the finger. The tapping event is **passed** to **next** layer, which is, the second item in the pic.

**Comment by DHM47** [comment]
Got it, thanks.

**Comment by DHM47** [comment]
Fixed, but I still have a few things to do before releasing

**Comment by DHM47** [comment]
Update Released,please check
