### ISSUE TITLE
Sort dialog items are not themeable

### ISSUE THREAD

**Issue by asdfasdfvful** [DHM47/Native-Clip-Board#41]
I will update you here. As of now, I don't think it's related to the material dialogs, so there's no need to add items. If you want, you could try defining the textcolor somewhere to help pinpoint where it is, but I believe it's appcompat related and I'll be looking into it.

You may view my progress here:

https://github.com/asdfasdfvful/Material-Glass/commits/master

**Comment by DHM47** [comment]
The material dialog library I'm using is made for Android Studio (gradle) while my app is still on Eclipse (ant) so porting the library is hard, that is why I haven't updated it yet (using 0.6.3.1 while latest is 0.7.4.1) .
I'll update and see if it gets fixed.

**Comment by asdfasdfvful** [comment]
Ah yes. That could be why

**Comment by DHM47** [comment]
Updating the library fixed it 
![](https://dl.pushbulletusercontent.com/T3alKtQyqBF3RmtV76nU7u8dLSnLF7By/Screenshot_2015-05-24-01-18-34.png)

**Comment by DHM47** [comment]
Can you try the 3.3.1 version.
http://forum.xda-developers.com/showpost.php?p=61279209&postcount=692
