### ISSUE TITLE
Lose Input focus in some app on Android 6.0

### ISSUE THREAD

**Issue by mikelei8291** [DHM47/Native-Clip-Board#50]
Such as Google Search bar on the launcher and in Google Translate app

Also, on the text field in the web pages with Firefox, the cursor is in the text field but when I tap the text in clip board it doesn't paste the text in the text field

**Comment by DHM47** [comment]
Those happen due to the fact that the clipboard is an activity. These apps work with the Accessibility approach just fine, that is why I'm considering make a hybrid mode to have the pros of both methods.

As for firefox, if it is not working there should be an error in the Xposed log

**Comment by mikelei8291** [comment]
Thanks
