### ISSUE TITLE
 "Clip board" button disappear in Chrome

### ISSUE THREAD

**Issue by mikelei8291** [DHM47/Native-Clip-Board#51]
With the beta release of fix issue #49, it works with a additional "Clip board" button, but it still doesn't work with long press "Paste" button

Also, the "Clip board" button disappear when I want to open clip board on the text field in web pages on Chrome

**Comment by DHM47** [comment]
It will no longer work with long click paste as that was a counter-intuitive approach. (What is the benefit of long click paste over the new button?)
As for it disappearing in Chrome, that is the correct issue.

**Comment by DHM47** [comment]
Can you test the 4.32 Beta 
http://forum.xda-developers.com/showpost.php?p=64435370&postcount=802

**Comment by DHM47** [comment]
What is the issue now ?

**Comment by mikelei8291** [comment]
The button is appear but it doesn't work at the text field in Chrome.

**Comment by DHM47** [comment]
Since which version of Chrome has this been happening?

**Comment by mikelei8291** [comment]
I think maybe in Chrome 48 and I'm using 49 now.

**Comment by DHM47** [comment]
Good, so it should be the same problem I fixed yesterday.
The update should be released tonight.
