### ISSUE TITLE
Marshmallow long press "paste" button support

### ISSUE THREAD

**Issue by benrap** [DHM47/Native-Clip-Board#52]
Can you guys add support to the marshmallow "paste" button as you had on lollipop? The long click support is what i mean.

**Comment by DHM47** [comment]
Have you tried the beta update in XDA? I've add a dedicated button instead of long clicking paste 
http://forum.xda-developers.com/showpost.php?p=64476381&postcount=814

**Comment by benrap** [comment]
Thanks, checking it out now!!

**Comment by DHM47** [comment]
So, is this issue still valid ?

**Comment by benrap** [comment]
Not valid anymore!! Thanks alot dev/s!!!!!!!!!!!! My favourite app in the playstore. So useful!
