### ISSUE TITLE
Unified calling direction

### ISSUE THREAD

**Issue by HankAviator** [DHM47/Native-Clip-Board#57]
Your user wants a unified direction of clipboard calling, so the clipboard will always take the place where IME has been. Add a switch to toggle between smart calling and custom position.

**Comment by DHM47** [comment]
Does the third option to keep the clipboard at the top necessary ?
Or should it be 
1-Adaptive 
2-Fixed to bottom

**Comment by HankAviator** [comment]
I myself only need it to be fixed to bottom in order to align with IME

**Comment by DHM47** [comment]
I just thought of another idea, how about just making it movable like when opened from accessibility? 
So I'll add an option smart positioning, when on it behaves like it is now. When off it will stay at the bottom, and of the user wants to uncover the text field he can do it manually.

**Comment by HankAviator** [comment]
Let's try it then! :clap:

**Comment by DHM47** [comment]
See this video demo for the new behavior
https://www.dropbox.com/s/6z0r3t2eaka2gi1/Screenshot_2016-01-30-15-16-11.png?dl=1
https://www.dropbox.com/s/fg7ga4eedz4vyus/Screencast_2016-01-30-15-15-23.mp4?dl=0

**Comment by HankAviator** [comment]
Looks nice, please implement it!

**Comment by DHM47** [comment]
Also, what should the default be ? On or Off ?

**Comment by HankAviator** [comment]
Off, but proudly show it off in changelog!

**Comment by HankAviator** [comment]
Oh, I meant on!)) Retain the old, current style to avoid doubts but let users know they can change the behavior
